### ISSUE TITLE
Default value feature

### ISSUE THREAD

**Issue by GreXLin85** [tomjschuster/sequelize-ui#86]
Operations may be easier if the ability to assign default values ​​to fields in models is added.

**Comment by tomjschuster** [comment]
@GreXLin85 #110 implements type-specific defaults. If you want to take a look, you can try it out at https://default-values.sequelize-ui.pages.dev/ or you can look at the examples in the PR description.

For the JSON/Array types, I'm currently only supporting defaulting to empty arrays or objects since I figured those were the most common use cases and didn't think it would be worth the effort/complexity to deal with validating JSON input fields and generating the code in a nice way. This is similar to how for the UUID/Date types I only support the generated UUID type or defaulting to the current time (rather than dealing with date time parsing, etc.).

If you have any feedback, I'll leave that PR up for about a week before merging.
